version: '3.8'

services:
  # ЕДИНСТВЕННЫЙ СЕРВИС: СЛУШАТЕЛЬ, ОБРАБОТЧИК И ГЕНЕРАТОР ОТЧЕТОВ
  listener:
    build: .
    container_name: retailcrm_listener
    restart: always
    env_file:
      - .env
    volumes:
      # Важно: монтируем папку для сохранения диалогов и отчетов
      - ./dialogs:/app/dialogs
    # Команда запускает main.py, который, в свою очередь, запускает
    # генератор отчетов в отдельном потоке по расписанию.
    command: python main.py