# docker-compose.yml
version: '3.8'

services:
  # 1. СЕРВИС СЛУШАТЕЛЯ
  listener:
    build: .
    container_name: retailcrm_listener
    restart: always
    # Используем среду (env) для передачи переменных из файла .env на хосте
    env_file:
      - .env
    volumes:
      # Монтируем директорию для хранения логов чатов
      - ./dialogs:/app/dialogs
    # Запускаем вашу точку входа
    command: python main.py

  # 2. СЕРВИС ЕЖЕДНЕВНЫХ ОТЧЕТОВ (Cron-задача)
  cron-reports:
    build: .
    container_name: retailcrm_cron
    restart: always
    env_file:
      - .env
    volumes:
      - ./dialogs:/app/dialogs

    # ! ФИНАЛЬНЫЙ РАБОЧИЙ ВАРИАНТ: Запуск только Cron-демона.
    command: cron -f