version: '3.8'

services:
  # 1. СЕРВИС СЛУШАТЕЛЯ (Без изменений)
  listener:
    build: .
    container_name: retailcrm_listener
    restart: always
    env_file:
      - .env
    volumes:
      - ./dialogs:/app/dialogs
    command: python main.py

  # 2. СЕРВИС ЕЖЕДНЕВНЫХ ОТЧЕТОВ (Cron-задача)
  cron-reports:
    build: .
    container_name: retailcrm_cron
    restart: always
    env_file:
      - .env
    volumes:
      - ./dialogs:/app/dialogs

    # ! ФИНАЛЬНЫЙ РАБОЧИЙ ВАРИАНТ 3.0:
    # Возвращаем простую команду, т.к. экспорт ENV теперь внутри скрипта run_report.sh.
    command: cron -f
